site_name: CMSC Copy-Paste Document

theme:
  name: material
  
  # 1. Features list (tabs, etc.)
  features:
    - navigation.tabs

  # 2. Palette: A list of two schemes (Light and Dark)
  palette:
    # Scheme 1: Light Mode (default)
    - scheme: default
      primary: black
      accent: yellow
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Scheme 2: Dark Mode
    - scheme: slate
      primary: black
      accent: yellow
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

# 3. Disable Search (Plural 'plugins')
plugins: [] 

nav:
  - HOME: index.md 

extra_javascript:
  - js/generator.js