site_name: UMBC Pre-Transfer Advising

theme:
  name: material
  palette:
    # This sets the dark mode background
    scheme: slate
    # This sets the primary color to black
    primary: black
    # This sets the accent color to yellow/gold for highlights
    accent: yellow
  features:
    - navigation.tabs

nav:
  - HOME: index.md 

extra_javascript:
  - js/generator.js